sonar.projectKey=deploy-project
sonar.projectName=Deploy Project
sonar.projectVersion=1.0

# Analyze backend Python code and frontend JS/JSX
sonar.sources=backend,frontend/src

# Exclude noise
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/*.pyc,**/dist/**

# Python version
sonar.python.version=3

# Source encoding
sonar.sourceEncoding=UTF-8